### ISSUE TITLE
Invalid Cert

### ISSUE THREAD

**Issue by shankera** [opencleveland/opencleveland.github.io#20]
The link on this repo, which goes to https://www.opencleveland.org does not have a valid cert, giving this error in chrome.
![this error](https://cloud.githubusercontent.com/assets/5796193/14694620/1a76d69e-0738-11e6-9ca0-9d7e867296e2.PNG)

**Comment by skorasaurus** [comment]
Hi, 
Thanks for the report. Where is the link that you're referring to? Is it in the description, like shown in ![selection_053](https://cloud.githubusercontent.com/assets/955351/14695264/6e2079d4-073e-11e6-885a-579390f139fd.png) ? 

If that link appears to be https for you, it may be because you have a browser extension/add-on (like https://www.eff.org/https-everywhere ) that forces all links to https. 

I'd like to enable HTTPS although our site is hosted through Gh-pages at the moment and github still doesn't support HTTPS on github pages

 (ref https://github.com/isaacs/github/issues/156)

**Comment by shankera** [comment]
Nope, it's on https://github.com/opencleveland, as seen in this screenshot: 
![capture](https://cloud.githubusercontent.com/assets/5796193/14698479/39ac3976-075d-11e6-97aa-6f300de60cde.PNG)

**Comment by shankera** [comment]
If GitHub pages doesn't support HTTPS this issue can likely be closed, but the URL should probably still be updated.

**Comment by pkoepke** [comment]
Thanks for letting us know, and for providing a screenshot! I fixed that link to point to HTTP instead of HTTPS.
